export const executions = [
    {
        id: 1,
        runName: "Welcome Email Flow",
        runTime: 12.5,
        stepsExecuted: 8,
        creditConsumed: 5,
        triggeredAt: "2025-03-04T09:30:00",
        completedAt: "2025-03-04T09:30:12",
        status: "completed",
        remark: "Successfully sent welcome email",
    },
    {
        id: 2,
        runName: "Order Confirmation",
        runTime: 8.2,
        stepsExecuted: 6,
        creditConsumed: 4,
        triggeredAt: "2025-03-04T10:15:00",
        completedAt: "2025-03-04T10:15:08",
        status: "completed",
        remark: "Order #12345 confirmed",
    },
    {
        id: 3,
        runName: "Lead Nurturing Sequence",
        runTime: 45.7,
        stepsExecuted: 3,
        creditConsumed: 12,
        triggeredAt: "2025-03-04T11:00:00",
        completedAt: null,
        status: "running",
        remark: "In progress",
    },
    {
        id: 4,
        runName: "Payment Reminder",
        runTime: 6.3,
        stepsExecuted: 5,
        creditConsumed: 3,
        triggeredAt: "2025-03-04T08:45:00",
        completedAt: "2025-03-04T08:45:06",
        status: "completed",
        remark: "Reminder sent successfully",
    },
    {
        id: 5,
        runName: "Customer Feedback Survey",
        runTime: 18.9,
        stepsExecuted: 7,
        creditConsumed: 8,
        triggeredAt: "2025-03-04T12:30:00",
        completedAt: "2025-03-04T12:30:19",
        status: "failed",
        remark: "Email delivery failed",
    },
    {
        id: 6,
        runName: "Abandoned Cart Recovery",
        runTime: 15.2,
        stepsExecuted: 9,
        creditConsumed: 7,
        triggeredAt: "2025-03-04T13:15:00",
        completedAt: "2025-03-04T13:15:15",
        status: "completed",
        remark: "Cart recovery email sent",
    },
    {
        id: 7,
        runName: "Product Recommendation",
        runTime: 22.6,
        stepsExecuted: 12,
        creditConsumed: 10,
        triggeredAt: "2025-03-04T14:00:00",
        completedAt: "2025-03-04T14:00:23",
        status: "completed",
        remark: "Recommendations generated",
    },
    {
        id: 8,
        runName: "Account Verification",
        runTime: 5.8,
        stepsExecuted: 4,
        creditConsumed: 2,
        triggeredAt: "2025-03-04T14:45:00",
        completedAt: "2025-03-04T14:45:06",
        status: "failed",
        remark: "User not found",
    },
    {
        id: 9,
        runName: "Subscription Renewal",
        runTime: 10.3,
        stepsExecuted: 7,
        creditConsumed: 5,
        triggeredAt: "2025-03-04T15:30:00",
        completedAt: "2025-03-04T15:30:10",
        status: "completed",
        remark: "Subscription renewed",
    },
    {
        id: 10,
        runName: "Data Sync Process",
        runTime: 35.7,
        stepsExecuted: 15,
        creditConsumed: 18,
        triggeredAt: "2025-03-04T16:15:00",
        completedAt: null,
        status: "running",
        remark: "Syncing in progress",
    },
];

// Table columns definition
export const columns = [
    { name: "Run Name", uid: "runName", sortable: true },
    { name: "Run Time(s)", uid: "runTime", sortable: true },
    { name: "Steps Executed", uid: "stepsExecuted", sortable: true },
    { name: "Credits Consumed", uid: "creditConsumed", sortable: true },
    { name: "Triggered at", uid: "triggeredAt", sortable: true },
    { name: "Completed/Failed at", uid: "completedAt", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Remark", uid: "remark" },
];

// Status options for filtering
export const statusOptions = [
    { name: "Completed", uid: "completed" },
    { name: "Failed", uid: "failed" },
    { name: "Running", uid: "running" },
];

// Status color mapping
export const statusColorMap = {
    completed: "success",
    failed: "danger",
    running: "warning",
};
