const channelIcons = [
    {
        name: "SMS",
        icon: "token-branded:chat",
        color: "#ffbe4e",
    },
    {
        name: "RCS",
        icon: "pajamas:image-comment-dark",
        // icon: "icon-park:message-one",
        // <Icon icon="pajamas:image-comment-dark"  style={{color: #c98d8d}} />
    },
    {
        name: "WhatsApp",
        icon: "logos:whatsapp-icon",
    },
    {
        name: "Email",
        icon: "skill-icons:gmail-light",
    },
];

const columns = [
    { name: "Name", uid: "contact_name", sortable: true },
    { name: "Mobile", uid: "phone_no", sortable: true },
    { name: "Channels", uid: "channels", sortable: true },
    { name: "Tags", uid: "tags", sortable: true },
    { name: "Actions", uid: "actions" },

    // { name: "Notes", uid: "notes" },
    // { name: "Last Interaction", uid: "date", sortable: true },
    // { name: "Email", uid: "email" },
    // { name: "Header", uid: "header", sortable: true },
    // { name: "Route", uid: "route", sortable: true },
    // { name: "Type", uid: "type", sortable: true },
    // { name: "Status", uid: "status", sortable: true },
    // { name: "Submitted Credits", uid: "submittedCredits", sortable: true },
    // { name: "Delivered Credits", uid: "deliveredCredits", sortable: true },
    // { name: "ID", uid: "id", sortable: true },
    // { name: "ROLE", uid: "role", sortable: true },
    // { name: "TEAM", uid: "team" },
];

const statusOptions = [
    { name: "Interested", uid: "interseted" },
    { name: "Not Interested", uid: "not_interseted" },
    { name: "Closed", uid: "closed" },
];

const users = [
    {
        id: 1,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        notes: "This person is interested in our product",
        channels: ["Email", "SMS", "WhatsApp"],
        email: "tony@example.com",
    },
    {
        id: 2,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: ["interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        notes: "This person is a potential customer",
        channels: ["Email", "RCS", "WhatsApp"],
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        notes: "This person is interested in our product",
        channels: ["Email", "SMS"],
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "William Howard",
        role: "C.M.",
        team: "Marketing",
        status: ["Not Interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        notes: "Avoid giving him too much attention",
        channels: ["Email", "SMS", "WhatsApp", "RCS"],
        email: "william.howard@example.com",
    },
    {
        id: 5,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Kristen Copper",
        role: "S. Manager",
        team: "Sales",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        notes: "He is facing some issues with campaigns",
        channels: ["SMS", "WhatsApp", "RCS"],
        email: "kristen.copper@example.com",
    },
    {
        id: 6,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Brian Kim",
        role: "P. Manager",
        team: "Management",
        status: ["interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        notes: "He is looking for new customers",
        channels: ["Email", "WhatsApp"],
        email: "brian.kim@example.com",
    },
    {
        id: 7,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Michael Hunt",
        role: "Designer",
        team: "Design",
        status: ["closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        notes: "See if you can sort this out",
        channels: ["SMS", "WhatsApp"],
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Samantha Brooks",
        role: "HR Manager",
        team: "HR",
        status: ["interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        notes: "This person is interested in our product",
        channels: ["RCS", "WhatsApp", "SMS"],
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Frank Harrison",
        role: "F. Manager",
        team: "Finance",
        status: ["Not Interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?img=4",
        notes: "Help him out",
        channels: ["WhatsApp", "Email"],
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Emma Adams",
        role: "Ops Manager",
        team: "Operations",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?img=5",
        notes: "Get him over call",
        channels: ["Email", "SMS", "WhatsApp", "RCS"],
        email: "emma.adams@example.com",
    },
];

function formatDate(date) {
    const options = {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "numeric",
        minute: "numeric",
        hour12: true,
    };
    return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export { columns, users, statusOptions, channelIcons };
