// (Name, Email, Created on, Created by, Role, Status (active, inactive), Actions (View with profile gear icon))

const columns = [
    { name: "Member", uid: "name", sortable: true },
    { name: "Created on", uid: "created_at", sortable: true },
    { name: "Created by", uid: "creator_name", sortable: true },
    { name: "Role", uid: "role", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Manage", uid: "manage" },

    // { name: "EMAIL", uid: "email" },
    // { name: "ID", uid: "id", sortable: true },
    // { name: "Header", uid: "header", sortable: true },
    // { name: "Route", uid: "route", sortable: true },
    // { name: "Type", uid: "type", sortable: true },
    // { name: "Submitted Credits", uid: "submittedCredits", sortable: true },
    // { name: "Delivered Credits", uid: "deliveredCredits", sortable: true },
    // { name: "TEAM", uid: "team" },
];

const statusOptions = [
    { name: "Active", uid: "active" },
    { name: "Inactive", uid: "inactive" },
];

const roleOptions = [
    { name: "Admin", uid: "admin" },
    { name: "Agent", uid: "agent" },
    { name: "Viewer", uid: "viewer" },
    { name: "Campaigner", uid: "campaigner" },
];

const users = [
    {
        id: 1,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Tony Reichert",
        createdBy: "Aasim Khan",
        role: "Admin",
        team: "Management",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Zoey Lang",
        createdBy: "Aasim Khan",
        role: "Agent",
        team: "Development",
        status: "inactive",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Jane Fisher",
        createdBy: "John Fitzgerald",
        role: "Viewer",
        team: "Viewer",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "William Howard",
        createdBy: "John Fitzgerald",
        role: "Campaigner",
        team: "Campaigner",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Kristen Copper",
        createdBy: "William Howard",
        role: "Admin",
        team: "Sales",
        status: "inactive",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Brian Kim",
        createdBy: "William Howard",
        role: "Admin",
        team: "Management",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "brian.kim@example.com",
    },
    {
        id: 7,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Michael Hunt",
        createdBy: "Frank Harrison",
        role: "Admin",
        team: "Design",
        status: "inactive",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Samantha Brooks",
        createdBy: "Aasim Khan",
        role: "Viewer",
        team: "HR",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Frank Harrison",
        role: "Agent",
        team: "Finance",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?img=4",
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Emma Adams",
        createdBy: "Aasim Khan",
        role: "Campaigner",
        team: "Operations",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?img=5",
        email: "emma.adams@example.com",
    },
];

function formatDate(date) {
    const options = {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "numeric",
        minute: "numeric",
        hour12: true,
    };
    return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export { columns, users, statusOptions, roleOptions };
