const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "NAME", uid: "name", sortable: true },
  { name: "Campaign", uid: "campaign", sortable: true },
  { name: "Mobile", uid: "mobile", sortable: true },
  { name: "Created at", uid: "date", sortable: true },
  { name: "AGE", uid: "age", sortable: true },
  { name: "ROLE", uid: "role", sortable: true },
  { name: "TEAM", uid: "team" },
  { name: "EMAIL", uid: "email" },
  { name: "Tags", uid: "status", sortable: true },
  { name: "Audience", uid: "submittedCredits", sortable: true },
  { name: "Submitted", uid: "deliveredCredits", sortable: true },
  { name: "Actions", uid: "actions" },
];

const statusOptions = [
  { name: "Completed", uid: "completed" },
  { name: "Failed", uid: "failed" },
  { name: "Pending", uid: "pending" },
];

const users = [
  {
    id: 1,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "failed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "pending",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
  },
  {
    id: 7,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "failed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "pending",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "failed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "failed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "failed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    date: formatDate(new Date()),
    campaign: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
    mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "completed",
    submittedCredits: Math.floor(Math.random() * 10) * 2,
    deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

function formatDate(date) {
  const options = {
    year: "2-digit",
    month: "2-digit",
    day: "2-digit",
    hour: "numeric",
    minute: "numeric",
    hour12: true,
  };
  return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export { columns, users, statusOptions };
