// Campaign Name | Date | RCS Devices | Non RCS Devices | Status | Submitted Credits | Delivered Credits | Actions |

const columns = [
    //   { name: "ID", uid: "id", sortable: true },
    { name: "Campaign Name", uid: "campaign_name", sortable: true },
    { name: "Date", uid: "created_at", sortable: true },
    { name: "Campaign Size", uid: "total", sortable: true },
    { name: "RCS Devices", uid: "rcs_devices", sortable: true },
    { name: "Non RCS Devices", uid: "nonrcs_devices", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Delivered Credits", uid: "deliveredCredits", sortable: true },
    { name: "Actions", uid: "actions" },

    //   { name: "Route", uid: "template_name", sortable: true },
    //   { name: "AGE", uid: "age", sortable: true },
    //   { name: "ROLE", uid: "role", sortable: true },
    //   { name: "TEAM", uid: "team" },
    //   { name: "EMAIL", uid: "email" },

    // { name: "NAME", uid: "name", sortable: true },
    // { name: "ROLE", uid: "role", sortable: true },
    // { name: "TEAM", uid: "team" },
    // { name: "EMAIL", uid: "email" },
];

const statusOptions = [
    { name: "Completed", uid: "completed" },
    { name: "Failed", uid: "failed" },
    { name: "Pending", uid: "pending" },
    { name: "Scheduled", uuid: "scheduled" },
];

const users = [
    {
        id: 1,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: "completed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: "failed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: "completed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "William Howard",
        role: "C.M.",
        team: "Marketing",
        status: "pending",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Kristen Copper",
        role: "S. Manager",
        team: "Sales",
        status: "completed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Brian Kim",
        role: "P. Manager",
        team: "Management",
        status: "completed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "brian.kim@example.com",
    },
    {
        id: 7,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Michael Hunt",
        role: "Designer",
        team: "Design",
        status: "failed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Samantha Brooks",
        role: "HR Manager",
        team: "HR",
        status: "completed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Frank Harrison",
        role: "F. Manager",
        team: "Finance",
        status: "pending",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?img=4",
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Emma Adams",
        role: "Ops Manager",
        team: "Operations",
        status: "completed",
        total: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?img=5",
        email: "emma.adams@example.com",
    },
];

function formatDate(date) {
    const options = {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "numeric",
        minute: "numeric",
        hour12: true,
    };
    return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export { columns, users, statusOptions };
