// campaign name | date | Route (API, Panel) | Type (p, t) | status | submitted telecredits | delivered credits |

const columns = [
    { name: "Campaign Name", uid: "campaignName", sortable: true },
    { name: "Date", uid: "date", sortable: true },
    { name: "Route", uid: "route", sortable: true },
    { name: "Type", uid: "type", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Submitted Credits", uid: "submitted_credits", sortable: true },
    { name: "Delivered Credits", uid: "deliverd_credits", sortable: true },

    // { name: "NAME", uid: "name", sortable: true },
    // { name: "AGE", uid: "age", sortable: true },
    // { name: "ROLE", uid: "role", sortable: true },
    // { name: "TEAM", uid: "team" },
    // { name: "EMAIL", uid: "email" },
    // { name: "Actions", uid: "actions" },
];

const statusOptions = [
    { name: "Credited", uid: "credited" },
    { name: "Deducted", uid: "deducted" },
];

const users = [
    {
        id: 1,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: "credited",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: "deducted",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "25",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: "credited",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "22",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "William Howard",
        role: "C.M.",
        team: "Marketing",
        status: "deducted",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "28",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Kristen Copper",
        role: "S. Manager",
        team: "Sales",
        status: "credited",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "24",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Brian Kim",
        role: "P. Manager",
        team: "Management",
        status: "credited",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "brian.kim@example.com",
    },
    {
        id: 7,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Michael Hunt",
        role: "Designer",
        team: "Design",
        status: "deducted",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "27",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Samantha Brooks",
        role: "HR Manager",
        team: "HR",
        status: "credited",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "31",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Frank Harrison",
        role: "F. Manager",
        team: "Finance",
        status: "deducted",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "33",
        avatar: "https://i.pravatar.cc/150?img=4",
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        campaignName: Math.random() < 0.5 ? "Marketing" : "Festival Sale",
        date: formatDate(new Date()),
        route: Math.random() < 0.5 ? "API" : "Panel",
        type: Math.random() < 0.5 ? "Transactional" : "Promotional",
        name: "Emma Adams",
        role: "Ops Manager",
        team: "Operations",
        status: "credited",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "35",
        avatar: "https://i.pravatar.cc/150?img=5",
        email: "emma.adams@example.com",
    },
];

function formatDate(date) {
    const options = {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "numeric",
        minute: "numeric",
        hour12: true,
    };
    return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export { columns, users, statusOptions };
