// Contact Name, Number, Channels, Tags, Notes, Last Interaction (Export & Import (single & bulk) btn at top)

const columns = [
    { name: "NAME", uid: "contact_name", sortable: true },
    { name: "Mobile", uid: "phone_no", sortable: true },
    { name: "Channels", uid: "channels", sortable: true },
    { name: "Tags", uid: "tags", sortable: true },
    { name: "Last Interaction", uid: "last_interaction", sortable: true },
    { name: "Notes", uid: "notes" },
    { name: "Actions", uid: "actions" },
    { name: "Email", uid: "email" },
];

const statusOptions = [
    { name: "Interested", uid: "Interested" },
    { name: "Not Interested", uid: "Not Interested" },
    { name: "Closed", uid: "Closed" },
];

const users = [
    {
        id: 1,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: ["interested", "closed", "not interested", "test tag"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        notes: "This person is interested in our product",
        channels: ["Email", "SMS", "WhatsApp"],
        email: "tony@example.com",
    },
    {
        id: 2,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: [
            "interested",
            "closed",
            "not interested",
            "test tag",
            "Interaction",
            "Final Review",
        ],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        notes: "This person is a potential customer",
        channels: ["Email", "RCS", "WhatsApp"],
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        notes: "This person is interested in our product",
        channels: ["Email", "SMS"],
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "William Howard",
        role: "C.M.",
        team: "Marketing",
        status: ["Not Interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        notes: "Avoid giving him too much attention",
        channels: ["Email", "SMS", "WhatsApp", "RCS"],
        email: "william.howard@example.com",
    },
    {
        id: 5,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Kristen Copper",
        role: "S. Manager",
        team: "Sales",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        notes: "He is facing some issues with campaigns",
        channels: ["SMS", "WhatsApp", "RCS"],
        email: "kristen.copper@example.com",
    },
    {
        id: 6,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Brian Kim",
        role: "P. Manager",
        team: "Management",
        status: ["interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        notes: "He is looking for new customers",
        channels: ["Email", "WhatsApp"],
        email: "brian.kim@example.com",
    },
    {
        id: 7,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Michael Hunt",
        role: "Designer",
        team: "Design",
        status: ["closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        notes: "See if you can sort this out",
        channels: ["SMS", "WhatsApp"],
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Samantha Brooks",
        role: "HR Manager",
        team: "HR",
        status: ["interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        notes: "This person is interested in our product",
        channels: ["RCS", "WhatsApp", "SMS"],
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Frank Harrison",
        role: "F. Manager",
        team: "Finance",
        status: ["Not Interested"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "Panel",
        avatar: "https://i.pravatar.cc/150?img=4",
        notes: "Help him out",
        channels: ["WhatsApp", "Email"],
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        date: formatDate(new Date()),
        header: Math.random() < 0.5 ? "TELEPIE" : "TSGNAL",
        type: Math.random() < 0.5 ? "transactional" : "promotional",
        mobile: Math.random() < 0.5 ? "+917345089454" : "+917645093454",
        name: "Emma Adams",
        role: "Ops Manager",
        team: "Operations",
        status: ["interested", "closed"],
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        route: "API",
        avatar: "https://i.pravatar.cc/150?img=5",
        notes: "Get him over call",
        channels: ["Email", "SMS", "WhatsApp", "RCS"],
        email: "emma.adams@example.com",
    },
];

function formatDate(date) {
    const options = {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "numeric",
        minute: "numeric",
        hour12: true,
    };
    return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export const cusmtomUsers = [
    {
        id: 1,
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: "active",
        age: "29",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: "paused",
        age: "25",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: "active",
        age: "22",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        name: "William Howard",
        role: "C.M.",
        team: "Marketing",
        status: "vacation",
        age: "28",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        name: "Kristen Copper",
        role: "S. Manager",
        team: "Sales",
        status: "active",
        age: "24",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/3.png",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        name: "Brian Kim",
        role: "P. Manager",
        team: "Management",
        age: "29",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png",
        email: "brian.kim@example.com",
        status: "active",
    },
    {
        id: 7,
        name: "Michael Hunt",
        role: "Designer",
        team: "Design",
        status: "paused",
        age: "27",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png",
        email: "michael.hunt@example.com",
    },
    {
        id: 8,
        name: "Samantha Brooks",
        role: "HR Manager",
        team: "HR",
        status: "active",
        age: "31",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/4.png",
        email: "samantha.brooks@example.com",
    },
    {
        id: 9,
        name: "Frank Harrison",
        role: "F. Manager",
        team: "Finance",
        status: "vacation",
        age: "33",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png",
        email: "frank.harrison@example.com",
    },
    {
        id: 10,
        name: "Emma Adams",
        role: "Ops Manager",
        team: "Operations",
        status: "active",
        age: "35",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/5.png",
        email: "emma.adams@example.com",
    },
    {
        id: 11,
        name: "Brandon Stevens",
        role: "Jr. Dev",
        team: "Development",
        status: "active",
        age: "22",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png",
        email: "brandon.stevens@example.com",
    },
    {
        id: 12,
        name: "Megan Richards",
        role: "P. Manager",
        team: "Product",
        status: "paused",
        age: "28",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/7.png",
        email: "megan.richards@example.com",
    },
    {
        id: 13,
        name: "Oliver Scott",
        role: "S. Manager",
        team: "Security",
        status: "active",
        age: "37",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png",
        email: "oliver.scott@example.com",
    },
    {
        id: 14,
        name: "Grace Allen",
        role: "M. Specialist",
        team: "Marketing",
        status: "active",
        age: "30",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/8.png",
        email: "grace.allen@example.com",
    },
    {
        id: 15,
        name: "Noah Carter",
        role: "IT Specialist",
        team: "I. Technology",
        status: "paused",
        age: "31",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png",
        email: "noah.carter@example.com",
    },
    {
        id: 16,
        name: "Ava Perez",
        role: "Manager",
        team: "Sales",
        status: "active",
        age: "29",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png",
        email: "ava.perez@example.com",
    },
    {
        id: 17,
        name: "Liam Johnson",
        role: "Data Analyst",
        team: "Analysis",
        status: "active",
        age: "28",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png",
        email: "liam.johnson@example.com",
    },
    {
        id: 18,
        name: "Sophia Taylor",
        role: "QA Analyst",
        team: "Testing",
        status: "active",
        age: "27",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png",
        email: "sophia.taylor@example.com",
    },
    {
        id: 19,
        name: "Lucas Harris",
        role: "Administrator",
        team: "Information Technology",
        status: "paused",
        age: "32",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png",
        email: "lucas.harris@example.com",
    },
    {
        id: 20,
        name: "Mia Robinson",
        role: "Coordinator",
        team: "Operations",
        status: "active",
        age: "26",
        avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
        email: "mia.robinson@example.com",
    },
];

export { columns, users, statusOptions };
