export const countries = [
  { key: "af", label: "Afrikaans" },
  { key: "sq", label: "Albanian" },
  { key: "ar", label: "Arabic" },
  { key: "az", label: "Azerbaijani" },
  { key: "bn", label: "Bengali" },
  { key: "bg", label: "Bulgarian" },
  { key: "ca", label: "Catalan" },
  { key: "zh_CN", label: "Chinese (CHN)" },
  { key: "zh_HK", label: "Chinese (HKG)" },
  { key: "zh_TW", label: "Chinese (TAI)" },
  { key: "hr", label: "Croatian" },
  { key: "cs", label: "Czech" },
  { key: "da", label: "Danish" },
  { key: "nl", label: "Dutch" },
  { key: "en", label: "English" },
  { key: "en_GB", label: "English (UK)" },
  { key: "en_US", label: "English (US)" },
  { key: "et", label: "Estonian" },
  { key: "fil", label: "Filipino" },
  { key: "fi", label: "Finnish" },
  { key: "fr", label: "French" },
  { key: "de", label: "German" },
  { key: "el", label: "Greek" },
  { key: "gu", label: "Gujarati" },
  { key: "he", label: "Hebrew" },
  { key: "hi", label: "Hindi" },
  { key: "hu", label: "Hungarian" },
  { key: "id", label: "Indonesian" },
  { key: "ga", label: "Irish" },
  { key: "it", label: "Italian" },
  { key: "ja", label: "Japanese" },
  { key: "kn", label: "Kannada" },
  { key: "kk", label: "Kazakh" },
  { key: "ko", label: "Korean" },
  { key: "lo", label: "Lao" },
  { key: "lv", label: "Latvian" },
  { key: "lt", label: "Lithuanian" },
  { key: "mk", label: "Macedonian" },
  { key: "ms", label: "Malay" },
  { key: "mr", label: "Marathi" },
  { key: "nb", label: "Norwegian" },
  { key: "fa", label: "Persian" },
  { key: "pl", label: "Polish" },
  { key: "pt_BR", label: "Portuguese (BR)" },
  { key: "pt_PT", label: "Portuguese (POR)" },
  { key: "pa", label: "Punjabi" },
  { key: "ro", label: "Romanian" },
  { key: "ru", label: "Russian" },
  { key: "sr", label: "Serbian" },
  { key: "sk", label: "Slovak" },
  { key: "sl", label: "Slovenian" },
  { key: "es", label: "Spanish" },
  { key: "es_AR", label: "Spanish (ARG)" },
  { key: "es_ES", label: "Spanish (SPA)" },
  { key: "es_MX", label: "Spanish (MEX)" },
  { key: "sw", label: "Swahili" },
  { key: "sv", label: "Swedish" },
  { key: "ta", label: "Tamil" },
  { key: "te", label: "Telugu" },
  { key: "th", label: "Thai" },
  { key: "tr", label: "Turkish" },
  { key: "uk", label: "Ukrainian" },
  { key: "ur", label: "Urdu" },
  { key: "uz", label: "Uzbek" },
  { key: "vi", label: "Vietnamese" },
  { key: "ka", label: "Georgian" },
  { key: "ha", label: "Hausa" },
  { key: "rw_RW", label: "Kinyarwanda" },
  { key: "ky_KG", label: "Kyrgyz (Kyrgyzstan)" },
  { key: "ml", label: "Malayalam" },
];
