// Sub accounts table cols: (Org ID, Org Name, Created on, Created by, Status, Last login.

const columns = [
    { name: "Organization ID", uid: "id", sortable: true },
    { name: "Organization Name", uid: "company", sortable: true },
    { name: "Created on", uid: "date", sortable: true },
    { name: "Created by", uid: "name", sortable: true },
    { name: "Status", uid: "status", sortable: true },
    { name: "Last Login", uid: "last_login", sortable: true },
    { name: "Actions", uid: "actions" },

    // { name: "NAME", uid: "name", sortable: true },
    // { name: "EMAIL", uid: "email" },
    // { name: "Route", uid: "route", sortable: true },
    // { name: "AGE", uid: "age", sortable: true },
    // { name: "ROLE", uid: "role", sortable: true },
    // { name: "TEAM", uid: "team" },
    // { name: "Submitted Credits", uid: "submittedCredits", sortable: true },
    // { name: "Delivered Credits", uid: "deliveredCredits", sortable: true },
];

const statusOptions = [
    { name: "Active", uid: "active" },
    { name: "Disabled", uid: "disabled" },
];

const users = [
    {
        id: 156,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
    },
    {
        id: 213,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: "disabled",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "25",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
    },
    {
        id: 356,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "22",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
    },
    {
        id: 401,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "William Howard",
        role: "C.M.",
        team: "Marketing",
        status: "disabled",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "28",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        email: "william.howard@example.com",
    },
    {
        id: 523,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Kristen Copper",
        role: "S. Manager",
        team: "Sales",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "24",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        email: "kristen.cooper@example.com",
    },
    {
        id: 609,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Brian Kim",
        role: "P. Manager",
        team: "Management",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "brian.kim@example.com",
    },
    {
        id: 174,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Michael Hunt",
        role: "Designer",
        team: "Design",
        status: "disabled",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "27",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        email: "michael.hunt@example.com",
    },
    {
        id: 128,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Samantha Brooks",
        role: "HR Manager",
        team: "HR",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "31",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        email: "samantha.brooks@example.com",
    },
    {
        id: 190,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Frank Harrison",
        role: "F. Manager",
        team: "Finance",
        status: "disabled",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "33",
        avatar: "https://i.pravatar.cc/150?img=4",
        email: "frank.harrison@example.com",
    },
    {
        id: 101,
        date: formatDate(new Date()),
        company: Math.random() < 0.5 ? "Telepie" : "Denver",
        route: Math.random() < 0.5 ? "transactional" : "promotional",
        name: "Emma Adams",
        role: "Ops Manager",
        team: "Operations",
        status: "active",
        submittedCredits: Math.floor(Math.random() * 10) * 2,
        deliveredCredits: [2, 4, 6][Math.floor(Math.random() * 3)],
        age: "35",
        avatar: "https://i.pravatar.cc/150?img=5",
        email: "emma.adams@example.com",
    },
];

function formatDate(date) {
    const options = {
        year: "2-digit",
        month: "2-digit",
        day: "2-digit",
        hour: "numeric",
        minute: "numeric",
        hour12: true,
    };
    return new Intl.DateTimeFormat("en-IN", options).format(date);
}

export { columns, users, statusOptions };
